class_name ClassDefs
## Static class definitions for the seven playable classes of
## Raven Hollow: Emberfall. Pure data + tiny helpers — no scene code.
##
## Class def shape (exact):
##   {id, name, title, lore, sheet, variant, max_hp, max_mana, speed,
##    hp_regen, mana_regen, color, abilities}
## Ability shape (exact, abilities[0] = basic attack, mana_cost 0):
##   {id, name, icon, cooldown, mana_cost, range, damage, kind, params}
## `kind` is one of: melee_arc, projectile, aoe_ring, dash, summon, buff, volley.
## `icon` is "pixel:<icon_id>" resolved through IconsPixel.get_tex — the
## icon_id of every ability equals its ability id (registry in icons_pixel.gd).
##
## Phase B.2 sprite-sheet VFX wiring (FXLib, scripts/fx_library.gd):
##   params.fx       — FXLib one-shot id, always equal to the ABILITY id
##                     (player.gd plays it at the mapped moment).
##   params.fx_loop  — FXLib looping-aura id: "consecration_loop" (persistent
##                     gold glyph), "divine_shield" (holy wrap on the player),
##                     "raise_dead_loop" (summon ellipse under the minion).
##   params.fx_tint  — optional Color passed as opts.tint to FXLib.play for
##                     effects the mapping wants re-tinted (smears = class
##                     color, shadowstep = near-black, war_cry = red-gold,
##                     grave_grasp = grave-purple).
##
## params conventions per kind (every params carries "color": the ability's
## VFX accent Color — muted, never neon):
##   melee_arc:  arc_degrees.
##   projectile: speed, projectile (flight-visual id string for
##               VFX.projectile_visual:
##               "spark"|"fireball"|"soul_bolt"|"arrow"|"fan_of_knives"|
##               "arrow_storm"; "orb" stays the procedural fallback),
##               optional aoe_radius (impact splash), thin (bool).
##   aoe_ring:   `range` = ring radius. at_aim (false = centered on self),
##               optional cast_range (max placement distance when at_aim),
##               tick_interval + duration (ticking consecrated ground —
##               render with VFX.ground_circle), slow_mult + slow_duration,
##               root_duration.
##   dash:       `range` = dash distance in px. smoke / feathers (bool VFX
##               flags), optional next_hit_mult + bonus_duration.
##   summon:     minion_type (enemy.gd sheet family, e.g. "skeleton"),
##               lifetime, minion_hp, minion_damage, minion_speed.
##   buff:       duration, optional speed_mult, damage_mult, absorb.
##   volley:     count, pattern ("radial" = burst around caster,
##               "rain" = arrows over aim area), speed, projectile (visual
##               kind), optional radius + duration (rain area / spread time).
##
## Sheet/variant picks verified by PIL crop of each sheet's down-facing idle
## frame (row = variant*3 + 1, col 0). All six are distinct and avoid the NPC
## cast combos (female1 v0, male2 v1, male3 v2, male4 v0, male2 v3,
## female2 v1, male1 v2):
##   warrior     male1 v0   — bearded, green quilted jerkin, sturdy.
##   rogue       male4 v3   — lean youth, all-dark shirt and trousers.
##   mage        female2 v3 — grey-haired wisewoman in long mauve robe.
##   paladin     male1 v1   — bearded, steel-blue padded gambeson.
##   necromancer male3 v1   — grim spectacled elder in long grey coat.
##   rookwarden  male2 v0   — huntsman in a weathered brown leather coat.

const _DEFS := {
	"warrior": {
		"id": "warrior",
		"name": "Warrior",
		"title": "Shield of the Hollow",
		"lore": "When the Emberfall razed the old garrison, only the drill-yard's stubbornness survived in him. Now he stands where the palisade burned, daring the dark to try Raven Hollow twice.",
		"sheet": "res://assets/art/characters/npc_male1.png",
		"variant": 0,
		"max_hp": 140.0,
		"max_mana": 55.0,
		"speed": 82.0,
		"hp_regen": 1.5,
		"mana_regen": 4.0,
		"color": Color(0.68, 0.30, 0.26),
		"abilities": [
			{
				"id": "cleave",
				"name": "Cleave",
				"icon": "pixel:cleave",
				"cooldown": 0.5,
				"mana_cost": 0.0,
				"range": 26.0,
				"damage": 12.0,
				"kind": "melee_arc",
				"params": {
					"arc_degrees": 110.0,
					"fx": "cleave",
					"fx_tint": Color(0.84, 0.78, 0.70),
					"color": Color(0.84, 0.78, 0.70),
				},
			},
			{
				"id": "shield_charge",
				"name": "Shield Charge",
				"icon": "pixel:shield_charge",
				"cooldown": 7.0,
				"mana_cost": 12.0,
				"range": 100.0,
				"damage": 0.0,
				"kind": "dash",
				"params": {
					"next_hit_mult": 1.8,
					"bonus_duration": 3.0,
					"fx": "shield_charge",
					"fx_tint": Color(0.66, 0.58, 0.48),
					"color": Color(0.62, 0.60, 0.58),
				},
			},
			{
				"id": "sunder",
				"name": "Sunder",
				"icon": "pixel:sunder",
				"cooldown": 8.0,
				"mana_cost": 15.0,
				"range": 30.0,
				"damage": 34.0,
				"kind": "melee_arc",
				"params": {
					"arc_degrees": 70.0,
					"fx": "sunder",
					"fx_tint": Color(0.92, 0.62, 0.50),
					"color": Color(0.80, 0.42, 0.34),
				},
			},
			{
				"id": "whirlwind",
				"name": "Whirlwind",
				"icon": "pixel:whirlwind",
				"cooldown": 6.0,
				"mana_cost": 16.0,
				"range": 40.0,
				"damage": 18.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": false,
					"fx": "whirlwind",
					"color": Color(0.75, 0.38, 0.30),
				},
			},
			{
				"id": "war_cry",
				"name": "War Cry",
				"icon": "pixel:war_cry",
				"cooldown": 12.0,
				"mana_cost": 15.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 5.0,
					"speed_mult": 1.4,
					"damage_mult": 1.3,
					"fx": "war_cry",
					"fx_tint": Color(0.90, 0.58, 0.30),
					"color": Color(0.88, 0.55, 0.28),
				},
			},
			{
				"id": "iron_bulwark",
				"name": "Iron Bulwark",
				"icon": "pixel:iron_bulwark",
				"cooldown": 16.0,
				"mana_cost": 15.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 6.0,
					"absorb": 40.0,
					"fx_loop": "iron_bulwark",
					"color": Color(0.60, 0.64, 0.68),
				},
			},
			{
				"id": "earthshaker",
				"name": "Earthshaker",
				"icon": "pixel:earthshaker",
				"cooldown": 30.0,
				"mana_cost": 32.0,
				"range": 72.0,
				"damage": 46.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": false,
					"slow_mult": 0.5,
					"slow_duration": 3.0,
					"fx": "earthshaker",
					"fx_tint": Color(0.66, 0.50, 0.40),
					"color": Color(0.58, 0.36, 0.28),
				},
			},
		],
	},
	"rogue": {
		"id": "rogue",
		"name": "Rogue",
		"title": "Knife in the Fog",
		"lore": "Raised in the fog-alleys behind the tavern, he learned young that a quiet knife settles what loud men cannot. The Hollow's shadows owe him favors, and he collects them nightly.",
		"sheet": "res://assets/art/characters/npc_male4.png",
		"variant": 3,
		"max_hp": 90.0,
		"max_mana": 50.0,
		"speed": 105.0,
		"hp_regen": 1.0,
		"mana_regen": 5.0,
		"color": Color(0.62, 0.62, 0.66),
		"abilities": [
			{
				"id": "quick_slash",
				"name": "Quick Slash",
				"icon": "pixel:quick_slash",
				"cooldown": 0.35,
				"mana_cost": 0.0,
				"range": 22.0,
				"damage": 8.0,
				"kind": "melee_arc",
				"params": {
					"arc_degrees": 90.0,
					"fx": "quick_slash",
					"fx_tint": Color(0.80, 0.80, 0.84),
					"color": Color(0.80, 0.80, 0.84),
				},
			},
			{
				"id": "backstab",
				"name": "Backstab",
				"icon": "pixel:backstab",
				"cooldown": 6.0,
				"mana_cost": 12.0,
				"range": 28.0,
				"damage": 24.0,
				"kind": "melee_arc",
				"params": {
					"arc_degrees": 60.0,
					"fx": "backstab",
					"fx_tint": Color(0.72, 0.16, 0.16),
					"color": Color(0.66, 0.20, 0.20),
				},
			},
			{
				"id": "shadowstep",
				"name": "Shadowstep",
				"icon": "pixel:shadowstep",
				"cooldown": 5.0,
				"mana_cost": 10.0,
				"range": 70.0,
				"damage": 0.0,
				"kind": "dash",
				"params": {
					"smoke": true,
					"next_hit_mult": 2.0,
					"bonus_duration": 3.0,
					"fx": "shadowstep",
					"fx_tint": Color(0.16, 0.15, 0.19),
					"color": Color(0.45, 0.44, 0.50),
				},
			},
			{
				"id": "noxious_vial",
				"name": "Noxious Vial",
				"icon": "pixel:noxious_vial",
				"cooldown": 8.0,
				"mana_cost": 18.0,
				"range": 34.0,
				"damage": 5.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": true,
					"cast_range": 120.0,
					"tick_interval": 0.5,
					"duration": 4.0,
					"slow_mult": 0.6,
					"slow_duration": 1.2,
					"fx": "venom_cloud",
					"fx_tint": Color(0.48, 0.62, 0.32),
					"color": Color(0.46, 0.60, 0.30),
				},
			},
			{
				"id": "fan_of_knives",
				"name": "Fan of Knives",
				"icon": "pixel:fan_of_knives",
				"cooldown": 7.0,
				"mana_cost": 20.0,
				"range": 110.0,
				"damage": 7.0,
				"kind": "volley",
				"params": {
					"count": 8,
					"pattern": "radial",
					"speed": 240.0,
					"projectile": "fan_of_knives",
					"fx": "fan_of_knives",
					"color": Color(0.75, 0.78, 0.82),
				},
			},
			{
				"id": "shroud",
				"name": "Shroud of Ash",
				"icon": "pixel:shroud",
				"cooldown": 12.0,
				"mana_cost": 20.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 4.0,
					"speed_mult": 1.35,
					"damage_mult": 1.2,
					"absorb": 30.0,
					"fx": "shroud",
					"fx_tint": Color(0.20, 0.20, 0.24),
					"color": Color(0.40, 0.40, 0.46),
				},
			},
			{
				"id": "death_blossom",
				"name": "Death Blossom",
				"icon": "pixel:death_blossom",
				"cooldown": 30.0,
				"mana_cost": 40.0,
				"range": 46.0,
				"damage": 10.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": false,
					"tick_interval": 0.4,
					"duration": 2.4,
					"fx": "death_blossom",
					"fx_tint": Color(0.72, 0.34, 0.34),
					"color": Color(0.70, 0.30, 0.30),
				},
			},
		],
	},
	"mage": {
		"id": "mage",
		"name": "Mage",
		"title": "Keeper of the Violet Flame",
		"lore": "She copied forbidden ember-script by candlelight until the candle answered back. The town council distrusts her violet fire, yet they knock on her door whenever the dark grows teeth.",
		"sheet": "res://assets/art/characters/npc_female2.png",
		"variant": 3,
		"max_hp": 80.0,
		"max_mana": 120.0,
		"speed": 90.0,
		"hp_regen": 0.6,
		"mana_regen": 8.0,
		"color": Color(0.62, 0.42, 0.78),
		"abilities": [
			{
				"id": "spark",
				"name": "Spark",
				"icon": "pixel:spark",
				"cooldown": 0.5,
				"mana_cost": 0.0,
				"range": 220.0,
				"damage": 9.0,
				"kind": "projectile",
				"params": {
					"speed": 260.0,
					"projectile": "spark",
					"fx": "spark",
					"color": Color(0.68, 0.45, 0.85),
				},
			},
			{
				"id": "ice_lance",
				"name": "Ice Lance",
				"icon": "pixel:ice_lance",
				"cooldown": 4.0,
				"mana_cost": 14.0,
				"range": 240.0,
				"damage": 18.0,
				"kind": "projectile",
				"params": {
					"speed": 320.0,
					"projectile": "ice_shard",
					"fx": "ice_lance",
					"color": Color(0.55, 0.72, 0.86),
				},
			},
			{
				"id": "fireball",
				"name": "Fireball",
				"icon": "pixel:fireball",
				"cooldown": 5.0,
				"mana_cost": 25.0,
				"range": 240.0,
				"damage": 22.0,
				"kind": "projectile",
				"params": {
					"speed": 200.0,
					"projectile": "fireball",
					"fx": "fireball",
					"aoe_radius": 30.0,
					"color": Color(0.92, 0.55, 0.25),
				},
			},
			{
				"id": "flame_strike",
				"name": "Flame Strike",
				"icon": "pixel:flame_strike",
				"cooldown": 7.0,
				"mana_cost": 35.0,
				"range": 44.0,
				"damage": 26.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": true,
					"cast_range": 130.0,
					"fx": "flame_strike",
					"color": Color(0.86, 0.40, 0.20),
				},
			},
			{
				"id": "frost_nova",
				"name": "Frost Nova",
				"icon": "pixel:frost_nova",
				"cooldown": 8.0,
				"mana_cost": 30.0,
				"range": 55.0,
				"damage": 10.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": false,
					"slow_mult": 0.5,
					"slow_duration": 3.0,
					"fx": "frost_nova",
					"color": Color(0.58, 0.76, 0.88),
				},
			},
			{
				"id": "blink",
				"name": "Blink",
				"icon": "pixel:arcane_blink",
				"cooldown": 6.0,
				"mana_cost": 15.0,
				"range": 90.0,
				"damage": 0.0,
				"kind": "dash",
				"params": {
					"smoke": true,
					"fx": "blink",
					"fx_tint": Color(0.64, 0.42, 0.82),
					"color": Color(0.60, 0.45, 0.82),
				},
			},
			{
				"id": "mana_shield",
				"name": "Mana Shield",
				"icon": "pixel:mana_shield",
				"cooldown": 16.0,
				"mana_cost": 22.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 6.0,
					"absorb": 55.0,
					"fx": "mana_shield",
					"fx_tint": Color(0.60, 0.55, 0.88),
					"color": Color(0.58, 0.56, 0.86),
				},
			},
			{
				"id": "cinderfall",
				"name": "Cinderfall",
				"icon": "pixel:meteor",
				"cooldown": 30.0,
				"mana_cost": 55.0,
				"range": 150.0,
				"damage": 14.0,
				"kind": "volley",
				"params": {
					"count": 12,
					"pattern": "rain",
					"radius": 60.0,
					"duration": 1.6,
					"speed": 320.0,
					"projectile": "fireball",
					"fx": "cinderfall",
					"color": Color(0.90, 0.46, 0.20),
				},
			},
		],
	},
	"paladin": {
		"id": "paladin",
		"name": "Paladin",
		"title": "Lantern of the Ashen Chapel",
		"lore": "Sworn at the ashen chapel on the hill, he carries the last consecrated hammer left in the Hollow. His faith is quiet, dented, and yet to break.",
		"sheet": "res://assets/art/characters/npc_male1.png",
		"variant": 1,
		"max_hp": 120.0,
		"max_mana": 70.0,
		"speed": 86.0,
		"hp_regen": 1.2,
		"mana_regen": 5.0,
		"color": Color(0.85, 0.68, 0.35),
		"abilities": [
			{
				"id": "hammer_blow",
				"name": "Hammer Blow",
				"icon": "pixel:hammer_blow",
				"cooldown": 0.6,
				"mana_cost": 0.0,
				"range": 26.0,
				"damage": 11.0,
				"kind": "melee_arc",
				"params": {
					"arc_degrees": 100.0,
					"fx": "hammer_blow",
					"color": Color(0.85, 0.68, 0.35),
				},
			},
			{
				"id": "holy_smite",
				"name": "Holy Smite",
				"icon": "pixel:holy_smite",
				"cooldown": 3.0,
				"mana_cost": 12.0,
				"range": 220.0,
				"damage": 16.0,
				"kind": "projectile",
				"params": {
					"speed": 240.0,
					"projectile": "bolt",
					"fx": "holy_smite",
					"color": Color(0.92, 0.82, 0.50),
				},
			},
			{
				"id": "judgment",
				"name": "Judgment",
				"icon": "pixel:judgment",
				"cooldown": 8.0,
				"mana_cost": 22.0,
				"range": 30.0,
				"damage": 20.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": true,
					"cast_range": 130.0,
					"root_duration": 1.25,
					"fx": "hammer_blow",
					"fx_tint": Color(1.0, 0.90, 0.55),
					"color": Color(0.90, 0.75, 0.42),
				},
			},
			{
				"id": "consecration",
				"name": "Consecration",
				"icon": "pixel:consecration",
				"cooldown": 9.0,
				"mana_cost": 30.0,
				"range": 45.0,
				"damage": 6.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": true,
					"cast_range": 110.0,
					"tick_interval": 0.5,
					"duration": 4.0,
					"fx": "consecration",
					"fx_loop": "consecration_loop",
					"color": Color(0.90, 0.75, 0.42),
				},
			},
			{
				"id": "lay_on_hands",
				"name": "Lay on Hands",
				"icon": "pixel:lay_on_hands",
				"cooldown": 16.0,
				"mana_cost": 30.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 1.5,
					"heal": 50.0,
					"fx": "holy_bloom",
					"color": Color(0.96, 0.90, 0.62),
				},
			},
			{
				"id": "divine_shield",
				"name": "Divine Shield",
				"icon": "pixel:divine_shield",
				"cooldown": 14.0,
				"mana_cost": 25.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 6.0,
					"absorb": 40.0,
					"fx_loop": "divine_shield",
					"color": Color(0.92, 0.80, 0.45),
				},
			},
			{
				"id": "sacred_bulwark",
				"name": "Sacred Bulwark",
				"icon": "pixel:sacred_bulwark",
				"cooldown": 22.0,
				"mana_cost": 35.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 8.0,
					"absorb": 70.0,
					"speed_mult": 1.2,
					"fx_loop": "holy_dome",
					"color": Color(0.88, 0.72, 0.40),
				},
			},
			{
				"id": "dawnbreak",
				"name": "Dawnbreak",
				"icon": "pixel:dawnbreak",
				"cooldown": 30.0,
				"mana_cost": 55.0,
				"range": 70.0,
				"damage": 55.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": true,
					"cast_range": 140.0,
					"root_duration": 1.5,
					"fx": "dawnbreak_pillar",
					"color": Color(1.0, 0.92, 0.60),
				},
			},
		],
	},
	"necromancer": {
		"id": "necromancer",
		"name": "Necromancer",
		"title": "Warden of the Old Graves",
		"lore": "Years tending Raven Hollow's graveyard taught him that the dead make loyal neighbors. He raises them politely, works them briefly, and always tucks them back in.",
		"sheet": "res://assets/art/characters/npc_male3.png",
		"variant": 1,
		"max_hp": 85.0,
		"max_mana": 110.0,
		"speed": 90.0,
		"hp_regen": 0.7,
		"mana_regen": 7.0,
		"color": Color(0.45, 0.72, 0.35),
		"abilities": [
			{
				"id": "soul_bolt",
				"name": "Soul Bolt",
				"icon": "pixel:soul_bolt",
				"cooldown": 0.55,
				"mana_cost": 0.0,
				"range": 220.0,
				"damage": 10.0,
				"kind": "projectile",
				"params": {
					"speed": 220.0,
					"projectile": "soul_bolt",
					"fx": "soul_bolt",
					"color": Color(0.55, 0.80, 0.38),
				},
			},
			{
				"id": "drain_life",
				"name": "Drain Life",
				"icon": "pixel:drain_life",
				"cooldown": 4.0,
				"mana_cost": 16.0,
				"range": 170.0,
				"damage": 22.0,
				"kind": "projectile",
				"params": {
					"speed": 185.0,
					"projectile": "soul_bolt",
					"fx": "drain_life",
					"lifesteal": 0.35,
					"color": Color(0.58, 0.40, 0.66),
				},
			},
			{
				"id": "withering_curse",
				"name": "Withering Curse",
				"icon": "pixel:withering_curse",
				"cooldown": 9.0,
				"mana_cost": 26.0,
				"range": 46.0,
				"damage": 5.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": true,
					"cast_range": 130.0,
					"tick_interval": 0.6,
					"duration": 4.0,
					"slow_mult": 0.6,
					"slow_duration": 1.2,
					"fx": "withering_curse",
					"fx_tint": Color(0.52, 0.66, 0.34),
					"color": Color(0.52, 0.66, 0.34),
				},
			},
			{
				"id": "bone_nova",
				"name": "Bone Nova",
				"icon": "pixel:bone_nova",
				"cooldown": 7.0,
				"mana_cost": 22.0,
				"range": 55.0,
				"damage": 16.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": false,
					"slow_mult": 0.55,
					"slow_duration": 2.0,
					"fx": "bone_nova",
					"fx_tint": Color(0.82, 0.80, 0.72),
					"color": Color(0.82, 0.80, 0.72),
				},
			},
			{
				"id": "grave_grasp",
				"name": "Grave Grasp",
				"icon": "pixel:grave_grasp",
				"cooldown": 8.0,
				"mana_cost": 25.0,
				"range": 40.0,
				"damage": 12.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": true,
					"cast_range": 120.0,
					"root_duration": 1.5,
					"fx": "grave_grasp",
					"fx_tint": Color(0.58, 0.38, 0.66),
					"color": Color(0.58, 0.38, 0.66),
				},
			},
			{
				"id": "bone_armor",
				"name": "Bone Armor",
				"icon": "pixel:bone_armor",
				"cooldown": 18.0,
				"mana_cost": 28.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 8.0,
					"absorb": 45.0,
					"damage_mult": 1.15,
					"fx": "bone_armor",
					"fx_loop": "bone_ward",
					"fx_tint": Color(0.62, 0.70, 0.52),
					"color": Color(0.62, 0.70, 0.52),
				},
			},
			{
				"id": "raise_dead",
				"name": "Raise Dead",
				"icon": "pixel:raise_dead",
				"cooldown": 12.0,
				"mana_cost": 35.0,
				"range": 80.0,
				"damage": 0.0,
				"kind": "summon",
				"params": {
					"minion_type": "skeleton",
					"lifetime": 20.0,
					"minion_hp": 35.0,
					"minion_damage": 6.0,
					"minion_speed": 75.0,
					"fx": "raise_dead",
					"fx_loop": "raise_dead_loop",
					"color": Color(0.50, 0.72, 0.40),
				},
			},
			{
				"id": "soul_harvest",
				"name": "Soul Harvest",
				"icon": "pixel:soul_harvest",
				"cooldown": 32.0,
				"mana_cost": 55.0,
				"range": 150.0,
				"damage": 12.0,
				"kind": "volley",
				"params": {
					"count": 14,
					"pattern": "rain",
					"radius": 70.0,
					"duration": 1.4,
					"speed": 300.0,
					"projectile": "soul_bolt",
					"fx": "soul_harvest",
					"color": Color(0.48, 0.74, 0.42),
				},
			},
		],
	},
	"rookwarden": {
		"id": "rookwarden",
		"name": "Hunter",
		"title": "Rookwarden of the Hollow",
		"lore": "The rooks of the Hollow choose one warden a generation, and they chose him at the gallows-tree. His arrows fly where the ravens point, and the ravens are never wrong.",
		"sheet": "res://assets/art/characters/npc_male2.png",
		"variant": 0,
		"max_hp": 95.0,
		"max_mana": 80.0,
		"speed": 98.0,
		"hp_regen": 0.9,
		"mana_regen": 6.0,
		"color": Color(0.24, 0.48, 0.50),
		"abilities": [
			{
				"id": "loosed_arrow",
				"name": "Loosed Arrow",
				"icon": "pixel:loosed_arrow",
				"cooldown": 0.45,
				"mana_cost": 0.0,
				"range": 260.0,
				"damage": 10.0,
				"kind": "projectile",
				"params": {
					"speed": 320.0,
					"projectile": "arrow",
					"fx": "loosed_arrow",
					"thin": true,
					"color": Color(0.76, 0.72, 0.60),
				},
			},
			{
				"id": "piercing_shot",
				"name": "Piercing Shot",
				"icon": "pixel:piercing_shot",
				"cooldown": 6.0,
				"mana_cost": 18.0,
				"range": 300.0,
				"damage": 22.0,
				"kind": "projectile",
				"params": {
					"speed": 420.0,
					"projectile": "arrow",
					"aoe_radius": 20.0,
					"thin": true,
					"fx": "piercing_shot",
					"color": Color(0.72, 0.74, 0.64),
				},
			},
			{
				"id": "snare_trap",
				"name": "Snare Trap",
				"icon": "pixel:snare_trap",
				"cooldown": 8.0,
				"mana_cost": 22.0,
				"range": 38.0,
				"damage": 8.0,
				"kind": "aoe_ring",
				"params": {
					"at_aim": true,
					"cast_range": 130.0,
					"root_duration": 1.6,
					"slow_mult": 0.5,
					"slow_duration": 2.5,
					"fx": "snare_trap",
					"fx_tint": Color(0.42, 0.56, 0.32),
					"color": Color(0.44, 0.58, 0.36),
				},
			},
			{
				"id": "raven_dash",
				"name": "Raven Dash",
				"icon": "pixel:raven_dash",
				"cooldown": 5.0,
				"mana_cost": 10.0,
				"range": 80.0,
				"damage": 0.0,
				"kind": "dash",
				"params": {
					"feathers": true,
					"fx": "raven_dash",
					"color": Color(0.30, 0.54, 0.56),
				},
			},
			{
				"id": "hunters_mark",
				"name": "Hunter's Mark",
				"icon": "pixel:hunters_mark",
				"cooldown": 14.0,
				"mana_cost": 20.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "buff",
				"params": {
					"duration": 6.0,
					"speed_mult": 1.1,
					"damage_mult": 1.35,
					"fx": "hunters_mark",
					"fx_tint": Color(0.60, 0.68, 0.44),
					"color": Color(0.58, 0.64, 0.42),
				},
			},
			{
				"id": "rook_companion",
				"name": "Rook Companion",
				"icon": "pixel:rook_companion",
				"cooldown": 20.0,
				"mana_cost": 30.0,
				"range": 0.0,
				"damage": 0.0,
				"kind": "summon",
				"params": {
					"minion_type": "raven",
					"lifetime": 18.0,
					"minion_hp": 45.0,
					"minion_damage": 8.0,
					"minion_speed": 108.0,
					"fx": "rook_companion",
					"fx_loop": "rook_companion_loop",
					"fx_tint": Color(0.20, 0.22, 0.26),
					"color": Color(0.28, 0.44, 0.48),
				},
			},
			{
				"id": "arrow_storm",
				"name": "Arrow Storm",
				"icon": "pixel:arrow_storm",
				"cooldown": 9.0,
				"mana_cost": 30.0,
				"range": 140.0,
				"damage": 8.0,
				"kind": "volley",
				"params": {
					"count": 10,
					"pattern": "rain",
					"radius": 45.0,
					"duration": 1.2,
					"speed": 300.0,
					"projectile": "arrow_storm",
					"fx": "arrow_storm",
					"color": Color(0.34, 0.54, 0.58),
				},
			},
			{
				"id": "storm_of_feathers",
				"name": "Storm of Feathers",
				"icon": "pixel:storm_of_feathers",
				"cooldown": 30.0,
				"mana_cost": 55.0,
				"range": 130.0,
				"damage": 14.0,
				"kind": "volley",
				"params": {
					"count": 20,
					"pattern": "radial",
					"speed": 300.0,
					"projectile": "arrow_storm",
					"fx": "storm_of_feathers",
					"color": Color(0.24, 0.34, 0.40),
				},
			},
		],
	},
	"druid": {
		"id": "druid",
		"name": "Druid",
		"title": "Warden of the Wildwood",
		"lore": "When the blight crept up out of the mire, she swore herself to the old wildwood that remembers Raven Hollow older than its walls. Root and storm answer her call now — though the forest, as it always does, will name its price.",
		"sheet": "res://assets/art/characters/npc_female1.png",
		"variant": 3,
		"max_hp": 100.0,
		"max_mana": 110.0,
		"speed": 88.0,
		"hp_regen": 1.4,
		"mana_regen": 6.5,
		"color": Color(0.36, 0.55, 0.30),
		"abilities": [
			{ "id": "maul", "name": "Maul", "icon": "pixel:maul",
				"cooldown": 0.5, "mana_cost": 0.0, "range": 26.0, "damage": 12.0, "kind": "melee_arc",
				"params": { "arc_degrees": 115.0, "fx": "maul", "fx_tint": Color(0.55, 0.62, 0.40), "color": Color(0.55, 0.62, 0.40) } },
			{ "id": "gale", "name": "Gale", "icon": "pixel:gale",
				"cooldown": 5.0, "mana_cost": 16.0, "range": 220.0, "damage": 20.0, "kind": "projectile",
				"params": { "speed": 250.0, "projectile": "gust_orb", "aoe_radius": 26.0, "fx": "gale", "color": Color(0.62, 0.78, 0.60) } },
			{ "id": "thornroot", "name": "Thornroot", "icon": "pixel:thornroot",
				"cooldown": 10.0, "mana_cost": 24.0, "range": 42.0, "damage": 11.0, "kind": "aoe_ring",
				"params": { "at_aim": true, "cast_range": 130.0, "root_duration": 1.6, "fx": "thornroot", "fx_tint": Color(0.42, 0.52, 0.28), "color": Color(0.42, 0.52, 0.28) } },
			{ "id": "stormbolt", "name": "Stormbolt", "icon": "pixel:stormbolt",
				"cooldown": 7.0, "mana_cost": 26.0, "range": 24.0, "damage": 24.0, "kind": "aoe_ring",
				"params": { "at_aim": true, "cast_range": 200.0, "slow_mult": 0.6, "slow_duration": 2.0, "fx": "stormbolt", "color": Color(0.70, 0.80, 0.92) } },
			{ "id": "rejuvenation", "name": "Rejuvenation", "icon": "pixel:rejuvenation",
				"cooldown": 12.0, "mana_cost": 30.0, "range": 0.0, "damage": 0.0, "kind": "buff",
				"params": { "duration": 6.0, "heal": 18.0, "heal_per_sec": 7.0, "fx": "heal_bloom", "color": Color(0.50, 0.75, 0.45) } },
			{ "id": "spirit_beast", "name": "Spirit Beast", "icon": "pixel:spirit_beast",
				"cooldown": 16.0, "mana_cost": 34.0, "range": 80.0, "damage": 0.0, "kind": "summon",
				"params": { "minion_type": "wolf", "lifetime": 22.0, "minion_hp": 42.0, "minion_damage": 7.0, "minion_speed": 92.0, "fx": "spirit_beast", "fx_loop": "spirit_beast_loop", "fx_tint": Color(0.55, 0.70, 0.50), "color": Color(0.55, 0.70, 0.50) } },
			{ "id": "bear_form", "name": "Bear Form", "icon": "pixel:bear_form",
				"cooldown": 18.0, "mana_cost": 30.0, "range": 0.0, "damage": 0.0, "kind": "buff",
				"params": { "duration": 8.0, "damage_mult": 1.4, "speed_mult": 1.1, "absorb": 35.0, "fx": "bear_form", "fx_tint": Color(0.55, 0.42, 0.28), "color": Color(0.55, 0.42, 0.28) } },
			{ "id": "tempest", "name": "Tempest", "icon": "pixel:tempest",
				"cooldown": 28.0, "mana_cost": 55.0, "range": 150.0, "damage": 9.0, "kind": "volley",
				"params": { "count": 12, "pattern": "rain", "radius": 70.0, "duration": 2.2, "speed": 300.0, "projectile": "spark", "fx": "tempest", "color": Color(0.62, 0.72, 0.86) } },
		],
	},
}


static func all_ids() -> Array[String]:
	var ids: Array[String] = [
		"warrior", "rogue", "mage", "paladin", "necromancer", "rookwarden",
		"druid",
	]
	return ids


## Returns a deep copy so callers may annotate it with runtime state without
## touching the read-only constants. Unknown ids warn and fall back to warrior.
static func get_def(id: String) -> Dictionary:
	if not _DEFS.has(id):
		push_warning("ClassDefs.get_def: unknown class id '%s', using warrior" % id)
		return (_DEFS["warrior"] as Dictionary).duplicate(true)
	return (_DEFS[id] as Dictionary).duplicate(true)
